theme: jekyll-theme-time-machine
title: Welcome to Computer Music!
description: This page gives information about the final project of the Computer Generated Music team in the software Design class at Olin College of Engineering.
